language: java
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jdk:
  - oraclejdk8
script: ./gradlew check --info
after_success:
  - ./gradlew jacocoTestReport coveralls
