language: java
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.gradle/go/
env:
  global:
    - GOGS_DIR=/home/travis/gogs
    - JAVA_OPTS=-Xmx1024m -XX:MaxPermSize=256m
jdk:
  - oraclejdk8
script: ./gradlew check --info --stacktrace
after_success:
  - ./gradlew jacocoTestReport coveralls
  - free -mt

before_install:
  - mkdir ~/gogs && git clone https://github.com/gogits/gogs.git ~/gogs
  - free -mt

after_failure:
  - free -mt
  - dmesg



