language: java
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.gradle/go/
env:
  - GOGS_DIR=/home/travis/gogs
  - JAVA_OPTS=-Xmx2048m -XX:MaxPermSize=256m
jdk:
  - oraclejdk8
script: ./gradlew check --info --no-daemon --stacktrace
after_success:
  - ./gradlew jacocoTestReport coveralls

before_install: mkdir ~/gogs && git clone https://github.com/gogits/gogs.git ~/gogs

