version: "{branch} {build}"
before_build:
  cmd: mkdir C:\gogs && git clone https://github.com/gogits/gogs.git C:\gogs
build_script:
  - gradlew check --info
cache:
  - C:\Users\appveyor\.gradle
environment:
  GOGS_DIR: C:\gogs
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0
matrix:
  fast_finish: true
