version: "{branch} {build}"
init:
  - git config --global core.autocrlf true
before_build:
  cmd: mkdir C:\gogs && git clone https://github.com/gogits/gogs.git C:\gogs
build_script:
  - gradlew check --info --no-daemon --stacktrace
environment:
  JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
  JAVA_OPTS: -Xmx1800m -XX:MaxPermSize=256m
  GOGS_DIR: C:\gogs
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0
matrix:
  fast_finish: true
